#version 450

// bn_fw 1st pass: calc mean

layout(binding = 0) readonly buffer InputBuf { float data[]; } buf_Input;
layout(binding = 1) writeonly buffer MeanBuf { float data[]; } buf_Mean;

layout(push_constant) uniform PushConstants {
    uint NHW;
    uint C;
} u_PC;

layout(local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

shared float shared_sum[256];

void main() {
    uint c = gl_WorkGroupID.x;
    uint thread_idx = gl_LocalInvocationID.x;
    uint num_threads = gl_WorkGroupSize.x;
    
    if (c >= u_PC.C) {
        return;
    }
    
    float local_sum = 0.0;
    for (uint idx = c + thread_idx * u_PC.C; idx < u_PC.NHW * u_PC.C; idx += num_threads * u_PC.C) {
        local_sum += buf_Input.data[idx];
    }
    shared_sum[thread_idx] = local_sum;
    barrier();
    for (uint stride = num_threads / 2; stride > 0; stride /= 2) {
        if (thread_idx < stride) {
            shared_sum[thread_idx] += shared_sum[thread_idx + stride];
        }
        barrier();
    }
    
    if (thread_idx == 0) {
        buf_Mean.data[c] = shared_sum[0] / float(u_PC.NHW);
    }
}
