#version 450

layout(binding = 0) readonly buffer InputBuf { float data[]; } buf_Output;
layout(binding = 1) readonly buffer OutputGradBuf { float data[]; } buf_OutputGrad;
layout(binding = 2) buffer InputGradBuf { float data[]; } buf_InputGrad;

layout(push_constant) uniform PushConstants {
    uint size;
} u_PC;

layout(local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

void main() {
    uint idx = gl_GlobalInvocationID.x;
    if (idx >= u_PC.size) {
        return;
    }
    buf_InputGrad.data[idx] = buf_OutputGrad.data[idx] * step(0.0, buf_Output.data[idx]);
}
